export const MODULE_CONFIG = {
  dashboard: { title: 'Dashboard', ecosystem: 'owner', enabled: true },
  activities: { title: 'Activity Center', ecosystem: 'owner', enabled: true },
  branches: { title: 'Branches', ecosystem: 'owner', enabled: true },
  bookings: { title: 'Bookings', ecosystem: 'owner', enabled: true },
  customers: { title: 'CRM', ecosystem: 'owner', enabled: true },
  staff: { title: 'Staff', ecosystem: 'owner', enabled: true },
  attendance: { title: 'Attendance', ecosystem: 'staff', enabled: true },
  services: { title: 'Services', ecosystem: 'owner', enabled: true },
  payments: { title: 'Payments', ecosystem: 'owner', enabled: true },
  payroll: { title: 'Payroll', ecosystem: 'owner', enabled: true },
  expenses: { title: 'Expenses', ecosystem: 'owner', enabled: true },
  finance: { title: 'Finance', ecosystem: 'owner', enabled: true },
  inventory: { title: 'Inventory', ecosystem: 'owner', enabled: true },
  suppliers: { title: 'Suppliers', ecosystem: 'owner', enabled: true },
  purchaseOrders: { title: 'Purchase Orders', ecosystem: 'owner', enabled: true },
  goodsReceiving: { title: 'Goods Receiving', ecosystem: 'owner', enabled: true },
  stockMovements: { title: 'Stock Movements', ecosystem: 'owner', enabled: true },
  analytics: { title: 'Analytics', ecosystem: 'owner', enabled: true },
  reports: { title: 'Reports', ecosystem: 'owner', enabled: true },
  websites: { title: 'Website Builder', ecosystem: 'owner', enabled: true },
  publicWebsites: { title: 'Public Website', ecosystem: 'customer', enabled: true },
  publicBookings: { title: 'Public Bookings', ecosystem: 'customer', enabled: true },
  notifications: { title: 'Notifications', ecosystem: 'core', enabled: true },
  search: { title: 'Global Search', ecosystem: 'core', enabled: true },
  localization: { title: 'Localization', ecosystem: 'core', enabled: true },
  whatsapp: { title: 'WhatsApp', ecosystem: 'core', enabled: false },
  loyalty: { title: 'Loyalty', ecosystem: 'owner', enabled: false },
  pos: { title: 'POS', ecosystem: 'owner', enabled: false },
  marketing: { title: 'Marketing', ecosystem: 'owner', enabled: false },
};

export const MODULE_ALIASES = {
  website: 'websites',
  publicWebsite: 'publicWebsites',
  publicBooking: 'publicBookings',
  purchaseOrders: 'purchaseOrders',
  'purchase-orders': 'purchaseOrders',
  goodsReceiving: 'goodsReceiving',
  'goods-receiving': 'goodsReceiving',
  stockMovements: 'stockMovements',
  'stock-movements': 'stockMovements',
  activity: 'activities',
  activityCenter: 'activities',
};

export const PLAN_MODULES = {
  premium: [
    'dashboard',
    'activities',
    'branches',
    'websites',
    'publicWebsites',
    'publicBookings',
    'bookings',
    'customers',
    'staff',
    'services',
    'payments',
    'payroll',
    'expenses',
    'finance',
    'inventory',
    'suppliers',
    'purchaseOrders',
    'goodsReceiving',
    'stockMovements',
    'analytics',
    'reports',
    'attendance',
    'notifications',
    'search',
    'localization',
    'whatsapp',
    'loyalty',
    'pos',
    'marketing',
  ],
  growth: [
    'dashboard',
    'activities',
    'branches',
    'websites',
    'publicWebsites',
    'publicBookings',
    'bookings',
    'customers',
    'staff',
    'services',
    'payments',
    'payroll',
    'expenses',
    'finance',
    'inventory',
    'suppliers',
    'purchaseOrders',
    'goodsReceiving',
    'stockMovements',
    'attendance',
    'analytics',
    'reports',
    'notifications',
    'search',
    'localization',
    'whatsapp',
    'loyalty',
  ],
  starter: [
    'dashboard',
    'activities',
    'websites',
    'publicWebsites',
    'publicBookings',
    'bookings',
    'customers',
    'staff',
    'services',
    'attendance',
    'notifications',
    'search',
    'localization',
  ],
  enterprise: Object.keys(MODULE_CONFIG),
};

export function getModulesForPlan(planCode = 'starter') {
  const normalizedPlanCode = String(planCode || 'starter').toLowerCase();
  return PLAN_MODULES[normalizedPlanCode] || PLAN_MODULES.starter;
}

export function isModuleEnabled(moduleKey, activeModules = []) {
  if (!moduleKey) return true;

  const normalizedModuleKey = MODULE_ALIASES[moduleKey] || moduleKey;
  const normalizedActiveModules = activeModules.map((key) => MODULE_ALIASES[key] || key);

  return MODULE_CONFIG[normalizedModuleKey]?.enabled !== false && normalizedActiveModules.includes(normalizedModuleKey);
}
