import {
  LayoutDashboard,
  Activity,
  CalendarCheck,
  Users,
  Globe,
  Package,
  Truck,
  FileText,
  PackageCheck,
  Clock,
  Wallet,
  Receipt,
  TrendingUp,
  BarChart2,
  Building2,
  CreditCard,
  ShieldCheck,
  ClipboardList,
  Timer,
  UserCheck,
} from 'lucide-react';

/**
 * Registry navigation definitions mapping to module, permissions, and layout sections.
 */
export const NAVIGATION_REGISTRY = [
  // Overview Section
  {
    id: 'dashboard',
    label: 'Dashboard',
    section: 'Overview',
    scope: 'admin',
    href: '/dashboard',
    icon: LayoutDashboard,
    permission: 'dashboard.view',
  },
  {
    id: 'daily-summary',
    label: 'Daily Summary',
    section: 'Overview',
    scope: 'admin',
    href: '/daily-summary',
    icon: Activity,
    module: 'analytics',
    permission: 'analytics.view',
  },

  // Operations Section
  {
    id: 'appointments',
    label: 'Appointments',
    section: 'Operations',
    scope: 'admin',
    href: '/appointments',
    icon: CalendarCheck,
    module: 'bookings',
    permission: 'booking.view',
  },
  {
    id: 'walk-in-desk',
    label: 'Walk-In Desk',
    section: 'Operations',
    scope: 'admin',
    href: '/reception',
    icon: ClipboardList,
    module: 'bookings',
    permission: 'booking.create',
  },
  {
    id: 'my-queue',
    label: 'My Queue',
    section: 'Operations',
    scope: 'admin',
    href: '/my-queue',
    icon: Timer,
    module: 'bookings',
    permission: 'booking.view',
  },
  {
    id: 'billing-queue',
    label: 'Billing Queue',
    section: 'Operations',
    scope: 'admin',
    href: '/billing-queue',
    icon: Receipt,
    module: 'bookings',
    permission: 'booking.billing',
  },
  {
    id: 'customers',
    label: 'Customers',
    section: 'Operations',
    scope: 'admin',
    href: '/customers',
    icon: Users,
    module: 'customers',
    permission: 'customer.view',
  },
  {
    id: 'revisit-center',
    label: 'Revisit Center',
    section: 'Operations',
    scope: 'admin',
    href: '/revisit-center',
    icon: UserCheck,
    module: 'customers',
    permission: 'customer.view',
  },
  {
    id: 'website',
    label: 'Website',
    section: 'Operations',
    scope: 'admin',
    href: '/website',
    icon: Globe,
    module: 'website',
    permission: 'website.view',
  },

  // Supply Chain Section
  {
    id: 'inventory',
    label: 'Inventory',
    section: 'Supply Chain',
    scope: 'admin',
    href: '/inventory',
    icon: Package,
    module: 'inventory',
    permission: 'inventory.view',
  },
  {
    id: 'suppliers',
    label: 'Suppliers',
    section: 'Supply Chain',
    scope: 'admin',
    href: '/suppliers',
    icon: Truck,
    module: 'inventory',
    permission: 'supplier.view',
  },
  {
    id: 'purchase-orders',
    label: 'Purchase Orders',
    section: 'Supply Chain',
    scope: 'admin',
    href: '/suppliers/purchase-orders',
    icon: FileText,
    module: 'inventory',
    permission: 'supplier.view',
  },
  {
    id: 'deliveries',
    label: 'Deliveries',
    section: 'Supply Chain',
    scope: 'admin',
    href: '/suppliers/deliveries',
    icon: PackageCheck,
    module: 'inventory',
    permission: 'supplier.view',
  },

  // Staff & Finance Section
  {
    id: 'staff-settings',
    label: 'Staff Settings',
    section: 'Staff & Finance',
    scope: 'admin',
    href: '/staff',
    icon: Users,
    module: 'staff',
    permission: 'staff.view',
  },
  {
    id: 'attendance',
    label: 'Attendance',
    section: 'Staff & Finance',
    scope: 'admin',
    href: '/attendance',
    icon: Clock,
    module: 'staff',
    permission: 'attendance.view',
  },
  {
    id: 'payroll',
    label: 'Payroll',
    section: 'Staff & Finance',
    scope: 'admin',
    href: '/payroll',
    icon: Wallet,
    module: 'staff',
    permission: 'payroll.view',
  },
  {
    id: 'expenses',
    label: 'Expenses',
    section: 'Staff & Finance',
    scope: 'admin',
    href: '/expenses',
    icon: Receipt,
    module: 'payments',
    permission: 'expenses.view',
  },
  {
    id: 'finance-pnl',
    label: 'Finance P&L',
    section: 'Staff & Finance',
    scope: 'admin',
    href: '/finance',
    icon: TrendingUp,
    module: 'payments',
    permission: 'finance.view',
  },

  // Insights Section
  {
    id: 'analytics',
    label: 'Analytics',
    section: 'Insights',
    scope: 'admin',
    href: '/analytics',
    icon: BarChart2,
    module: 'analytics',
    permission: 'analytics.view',
  },
  {
    id: 'payments',
    label: 'Payments',
    section: 'Insights',
    scope: 'admin',
    href: '/payments',
    icon: Wallet,
    module: 'payments',
    permission: 'payment.view',
  },

  // Super Admin Platform Section
  {
    id: 'platform-overview',
    label: 'Platform Overview',
    section: 'Platform',
    scope: 'superadmin',
    href: '/superadmin/dashboard',
    icon: LayoutDashboard,
    permission: 'platform.dashboard.view',
  },
  {
    id: 'salon-tenants',
    label: 'Salon Tenants',
    section: 'Platform',
    scope: 'superadmin',
    href: '/superadmin/tenants',
    icon: Building2,
    permission: 'platform.tenants.view',
  },
  {
    id: 'subscriptions',
    label: 'Subscriptions',
    section: 'Platform',
    scope: 'superadmin',
    href: '/superadmin/subscriptions',
    icon: CreditCard,
    permission: 'platform.subscriptions.view',
  },
  {
    id: 'approvals',
    label: 'Approvals',
    section: 'Platform',
    scope: 'superadmin',
    href: '/superadmin/approvals',
    icon: ShieldCheck,
    permission: 'platform.approvals.view',
  },
  {
    id: 'platform-analytics',
    label: 'Platform Analytics',
    section: 'Platform',
    scope: 'superadmin',
    href: '/superadmin/analytics',
    icon: BarChart2,
    permission: 'platform.analytics.view',
  },
];

export default NAVIGATION_REGISTRY;
